config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user  do
    get 'users/info', to: 'users/infos#info'
    post 'users/info', to: 'users/infos#setting'
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        member do
          post :invite_member
        end
      end
    end
  end

  resource :personal, only: [:show]

  resources :projects, except: [:index] do
    resource :bucket, only: [:show] do
      resources :documents, only: %i[create destroy]
    end
    resource :chat_room, only: [:show] do
      resources :contents, only: [:create]
    end
    resources :private_chats, only: [:show] do
      resources :contents, only: [:create]
    end

    resources :schedules
    resources :messages do
      resources :comments, only: %i[create destroy edit]
    end

    resources :todo_lists do
      member do
        patch :move
      end
      resources :todo_items
    end
  end

  mount DocumentUploader.download_endpoint => '/documents', host: 'https://turbocamp.tw'
  mount ImageUploader.download_endpoint => '/images', host: 'https://turbocamp.tw'
end

app/models/bucket.rb
# frozen_string_literal: true

class Bucket < ApplicationRecord
  belongs_to :project
  has_many :documents, dependent: :destroy

  def self.all_status
    [
      %w[草稿 draft],
      %w[發佈 published]
    ]
  end
end

app/models/chat_room.rb
# frozen_string_literal: true

class ChatRoom < ApplicationRecord
  belongs_to :project
  has_many :contents, as: :contentable, dependent: :destroy
  has_many :chat_users 
  has_many :users , through: :chat_users , dependent: :destroy

end

app/models/chat_user.rb
class ChatUser < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
  validates :content , presence: true
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  include ImageUploader::Attachment(:image)
  validates :text, presence: true, unless: :image_data
  belongs_to :user
  belongs_to :contentable, polymorphic: true
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  belongs_to :bucket
  include DocumentUploader::Attachment(:document)
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    before_create :generate_token

    belongs_to :user
    validates :email, presence: true
   


    def generate_token
      self.token = SecureRandom.urlsafe_base64
    end

    def clear_token
      self.update(token: nil)
    end

end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  include Visible
  include Slugable

  belongs_to :project
  has_many :comments, dependent: :destroy
  # belongs_to :project

  validates :title, presence: true
end

app/models/personal.rb
# frozen_string_literal: true

class Personal < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/private_chat.rb
# frozen_string_literal: true

class PrivateChat < ApplicationRecord
  belongs_to :project
  has_many :user_privates
  has_many :users, through: :user_privates, dependent: :destroy
  has_many :contents, as: :contentable, dependent: :destroy

  def self.find_or_create(users, project_id)
    users_ids = users.map(&:id).sort
    name = "Room:#{users_ids.join('-')}"
    if private_chat = where(roomname: name).first
    else
      private_chat = PrivateChat.new(roomname: name, project_id:)
      private_chat.users = users
      private_chat.save
    end
    private_chat
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  after_create :create_chat_room
  after_create :create_bucket
  include ImageUploader::Attachment(:image)
  include Slugable

  #  與user多對多關聯
  has_many :personals
  has_many :users, through: :personals, dependent: :destroy

  # 在project內部功能
  has_many :private_chats, dependent: :destroy
  has_one :chat_room, dependent: :destroy
  has_one :bucket, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :schedules,  dependent: :destroy
  has_many :todo_lists, dependent: :destroy
  has_many :todo_lists, -> { order(position: :asc) }

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 50 }

  def normalize_friendly_id(value)
    value.to_s.parameterize(preserve_case: true)
  end
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  # has_many :todo_lists

  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :location, presence: true
  belongs_to :project
end

app/models/todo_item.rb
# frozen_string_literal: true

class TodoItem < ApplicationRecord
  belongs_to :todo_list

  scope :completed, lambda {
    where(completed: true)
  }

  validates :description, presence: true
end

app/models/todo_list.rb
# frozen_string_literal: true

class TodoList < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
  has_many :todo_items, dependent: :destroy
  # has_one :schedules, dependent: :destroy

  def percent_complete
    return 0 if total_items.zero?

    (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Slugable
  include AvatarUploader::Attachment(:avatar)

  has_many :chat_users 
  has_many :chat_rooms , through: :chat_users , dependent: :destroy
  has_many :personals
  has_many :projects, through: :personals, dependent: :destroy
  has_many :user_privates
  has_many :private_chats, through: :user_privates, dependent: :destroy
  has_many :contents
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]

  def self.create_from_provider_data(provider_data)
    where(email: provider_data.info.email).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.nickname = provider_data.info.name
      user.provider = provider_data.provider
      user.uid = provider_data.uid
      user.imageurl = provider_data.info.image
    end
  end

  def normalize_friendly_id(value)
    value.to_s.parameterize(preserve_case: true)
  end
end

app/models/user_private.rb
# frozen_string_literal: true

class UserPrivate < ApplicationRecord
  belongs_to :private_chat
  belongs_to :user
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div data-controller="notification"
         data-notification-delay-value="3500"
         class="fixed top-24 right-14 z-50 transform duration-1000 hidden"
         data-transition-enter-from="opacity-0 -translate-y-6"
         data-transition-enter-to="opacity-100 translate-y-0"
         data-transition-leave-from="opacity-100 -translate-y-0"
         data-transition-leave-to="opacity-0 translate-y-6"
         role="alert">
      <div class="flash-alert">
        <div class="flex flex-wrap px-4 py-2 font-medium">
          #{messages}
        </div>
        <button data-action="notification#hide">
          <i class="fa-regular fa-circle-xmark pr-3"></i>
        </button>
      </div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/markdown_helper.rb
# frozen_string_literal: true

module MarkdownHelper
  def markdown(content)
    tag.article data: { controller: 'markdown-viewer' }, class: "markdown" do
      content
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/message_boards/index.html.erb
<div class="bg-white pt-16 pb-20 px-4 sm:px-6 lg:pt-24 lg:pb-28 lg:px-8">
  <div class="relative max-w-lg mx-auto divide-y-2 divide-gray-200 lg:max-w-7xl">
    <div>
      <h2 class="text-3xl tracking-tight font-extrabold text-gray-900 sm:text-4xl">Message Board</h2>
      <div class="mt-3 sm:mt-4 lg:grid lg:grid-cols-2 lg:gap-5 lg:items-center">
        <form class="mt-6 flex flex-col sm:flex-row lg:mt-0 lg:justify-end">
          <div class="mt-2 flex-shrink-0 w-full flex rounded-md shadow-sm sm:mt-0 sm:ml-3 sm:w-auto sm:inline-flex">
            <button class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out">
              <%= link_to "New messages", new_message_path%>
            </button>
          </div>
        </form>
      </div>
    </div>
    <% @messages.each do |message|%>
      <% if message.public? %>
        <div class="mt-6 pt-10 grid gap-16 lg:grid-cols-2 lg:gap-x-5 lg:gap-y-12">
          <div>
            <p class="text-sm text-gray-500">
              <time datetime="2020-03-16"><%= message.updated_at%></time>
            </p>
            <div class="mt-2 block">
              <h2 class="text-xl font-semibold text-gray-900"><%= message.title%> </h2>
              <p class="mt-3 text-base text-gray-500"><%= message.content%></p>
            </div>
            <div class="mt-3">
              <%= link_to "Read More", message_path(message.id), class:"ttext-base font-semibold text-indigo-600 hover:text-indigo-500"%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_aside.html.erb
<div class="w-full max-h-full h-full bg-theme-50 px-1">
  <div class="py-6 px-5">
    <div class="flex items-center">
      <div class="h-14 w-14 overflow-hidden rounded-full">
        <%= image_tag(@project.image_url || "logo_a_0" , class:"w-full h-full")%>
      </div>
      <div class="flex-grow pl-5">
        <h2 class="self-center text-xl font-semibold whitespace-nowrap"><%= @project&.title %></h2>
      </div>
      <div class="justify-end">
        <button type="button" data-action="click->toggle#close">
          <%= icon_tag('fa-solid fa-angles-left fa-lg text-gray-600 md:opacity-0 transition-opacity duration-100 ease-out') %>
        </button>
      </div>
    </div>
  </div>
  <ul class="relative">
    <li class="relative">
      <% if policy(@project).update? %>
        <%= link_to icon_tag('fa-solid fa-sliders fa-lg pr-5', 'Project Edit'), edit_project_path(@project), class: 'sidebar-link', data: { remote: true } %>
      <% end %>
    </li>
    <div class="py-4 w-full">
      <hr>
    </div>
    <li class="relative <%= 'sidebar-active' if current_page?(project_todo_lists_path(@project)) %>">
      <%= sidebar_link_with_icon project_todo_lists_path(@project), 
          icon_tag('fa-regular fa-check-circle fa-lg pr-5','Todos') %>
    </li>
    <li class="<%= 'sidebar-active' if current_page?(project_schedules_path(@project))%>">
      <%= sidebar_link_with_icon project_schedules_path(@project),
          icon_tag('fa-regular fa-calendar-alt fa-lg pr-6', 'Schedule') %>
    </li>
    <li class="relative <%= 'sidebar-active' if current_page?(project_chat_room_path(@project))%>">
      <%= sidebar_link_with_icon project_chat_room_path(@project), icon_tag('fa-regular fa-comment fa-lg pr-5', 'Chatroom') %>
      <% if current_user.chat_users.find_by(chat_room_id:@project.chat_room.id).unread_count >0 %>
      <span class="absolute right-2 bottom-1/3 rounded-full bg-red-800 text-white text-md px-2 py-0"><%= current_user.chat_users.find_by(chat_room_id:@project.chat_room.id).unread_count %></span>
      <% end %> 
    </li>
    <li class="<%= 'sidebar-active' if current_page?(project_messages_path(@project))%>">
      <%= sidebar_link_with_icon project_messages_path(@project),
          icon_tag('fa-regular fa-chart-bar fa-lg pr-5', 'Message Boards') %>
    </li>
    <li class="<%= 'sidebar-active' if current_page?(project_bucket_path(@project))%>">
      <%= sidebar_link_with_icon project_bucket_path(@project),
          icon_tag('fa-solid fa-cloud-arrow-up fa-lg pr-3.5', 'Upload') %>
    </li>
  </ul>
</div>
<div class="w-full h-18 px-5 py-3 bg-theme-100">
  <div class="flex justify-between items-center">
    <div class="flex justify-start items-center">
      <div class="w-12 h-12 rounded-full overflow-hidden">
        <%= image_tag(current_user.avatar_url || current_user.imageurl || "default_user", size:'64x64') %>
      </div>
      <div class="pl-4 text-gray-500 text-xl font-medium">
        <%= current_user.nickname %>
      </div>
    </div>
    <div class="relative text-gray-500 text-xl font-medium">
      <%= link_to icon_tag('fa-solid fa-gear p-2'), users_info_path(current_user), data: { remote: true } %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div data-controller="notification"
     data-notification-delay-value="3000"
     class="fixed top-20 right-10  md:top-20 md:right-24 z-50 transform duration-1000 hidden"
     data-transition-enter-from="opacity-0 -translate-y-6"
     data-transition-enter-to="opacity-100 translate-y-0"
     data-transition-leave-from="opacity-100 -translate-y-0"
     data-transition-leave-to="opacity-0 translate-y-6"
     role="alert">
  <% flash.each do |type, msg| %>
  <div class="flash-<%= type %>">
    <p class="px-4 py-2 font-medium"><%= msg %></p>
    <button data-action="notification#hide">
      <%= icon_tag('fa-regular fa-circle-xmark pr-3') %>
    </button>
  </div>
  <% end %>
</div>

app/views/shared/_friendbar.html.erb
<div class"flex flex-col border-gray-400 border-l ">
  <% (@project.users - [current_user]).each do |user| %>
    <div class="relative" id="notice">
      <%= link_to project_private_chat_path(@project , user.id ) , user_id: user.id, private_chat_id: PrivateChat.find_or_create( [current_user , user] , @project.id).id , class:"m-0 p-0" do %>
        <%= image_tag(user.avatar_url || user.imageurl || "default_user" , size:"45x45" , class:'rounded-full my-2 mx-auto') %>
      <% end %>
      <% if current_user.user_privates.find_by(private_chat_id: PrivateChat.find_or_create( [current_user , user] , @project.id).id).unread_count >0 %>
        <span class="absolute bottom-0 left-3 px-1 py-0 bg-red-800 rounded-full text-xs text-white"><%= current_user.user_privates.find_by(private_chat_id: PrivateChat.find_or_create( [current_user , user] , @project.id).id).unread_count %></span>
      <% end %>
    </div>
  <% end %>
  <div data-controller="member" class="my-2 flex justify-center align-middle" data-id="<%= @project.slug%>"> 
    <div data-toggle-target="addBtn" class="h-11 w-11 rounded-full border border-gray-300 flex justify-center align-middle opacity-0">
      <button data-action="click->member#join" class="text-2xl text-gray-500 flex justify-center items-center ">
        <i class="fas fa-plus"></i>
      </button>
    </div>
    <div id="inputbox" class=" bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full hidden">
    <div class="bg-white rounded-lg py-5 px-10">
        <div class="border-b border-gray-300 mb-5 flex justify-between">
          <h3 class=" mb-2 text-xl font-medium text-gray-900 dark:text-white">
            Add member
          </h3>
          <div >
            <button data-action="click->member#cancel"><i class="fas fa-times text-2xl"></i></button>
          </div>
        </div>
        <div>
          <input type="text" placeholder="Enter the email address..." class="input border border-gray-400 rounded-md p-1">
          <button class="searchbtn theme-fill-btn" data-action="click->member#invite">Invite</button>
        </div>
    </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<div data-modal-target="container" class="hidden bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
      <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
              <h3 class="text-xl font-medium text-gray-900 dark:text-white">
                  Default modal
              </h3>
              <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="medium-modal">
                  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>  
              </button>
          </div>
          <div class="p-6 space-y-6">
              <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                  With less than a month to go before the European Union enacts new consumer privacy laws for its citizens, companies around the world are updating their terms of service agreements to comply.
              </p>
              <p class="text-base leading-relaxed text-gray-500 dark:text-gray-400">
                  The European Union’s General Data Protection Regulation (G.D.P.R.) goes into effect on May 25 and is meant to ensure a common set of data rights in the European Union. It requires organizations to notify users as soon as possible of high-risk data breaches that could personally affect them.
              </p>
          </div>
          <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
              <button data-modal-toggle="medium-modal" type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">I accept</button>
              <button data-modal-toggle="medium-modal" type="button" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">Decline</button>
          </div>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-theme-5 border-theme-100 filter drop-shadow-sm border-b w-full h-15 p-1">
  <div class="sidebar-toggle-btn">
    <button type="button" data-action="click->toggle#open">
      <%= icon_tag('fa-solid fa-bars fa-lg text-gray-600') %>
    </button>
  </div>
  <div class="flex flex-row justify-end items-center h-7 my-4">
    <div class="flex flex-row items-center">
      <button type="button" data-action="click->toggle#toggle">
        <%= icon_tag('fa-user-group fa-solid fa-lg pr-5 text-gray-600') %>
      </button>
      <%= link_to icon_tag('fa-house-user fa-solid fa-lg pr-5 text-gray-600'), project_path(@project) if @project %>
      <%= link_to icon_tag('fa-table-cells fa-solid fa-lg pr-5 text-gray-600'), personal_path, method: :get %>
      <%= link_to icon_tag('fa-arrow-right-from-bracket fa-solid fa-lg pr-5 text-gray-600'), destroy_user_session_path, method: :delete %>
    </div>
  </div>
</nav>