config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user  do
    get 'users/info', to: 'users/infos#info'
    post 'users/info', to: 'users/infos#setting'
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        member do
          post :invite_member
        end
      end
    end
  end

  resource :personal, only: [:show]

  resources :projects, except: [:index] do
    resource :bucket, only: [:show] do
      resources :documents, only: %i[create destroy]
    end
    resource :chat_room, only: [:show] do
      resources :contents, only: [:create]
    end
    resources :private_chats, only: [:show] do
      resources :contents, only: [:create]
    end

    resources :schedules
    resources :messages do
      resources :comments, only: %i[create destroy edit]
    end

    resources :todo_lists do
      member do
        patch :move
      end
      resources :todo_items
    end
  end

  mount DocumentUploader.download_endpoint => '/documents', host: 'https://turbocamp.tw'
  mount ImageUploader.download_endpoint => '/images', host: 'https://turbocamp.tw'
end

app/models/todo_list.rb
# frozen_string_literal: true

class TodoList < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
  has_many :todo_items, dependent: :destroy
  # has_one :schedules, dependent: :destroy

  def percent_complete
    return 0 if total_items.zero?

    (100 * completed_items.to_f / total_items).round(1)
  end

  def completed_items
    @completed_items ||= todo_items.completed.count
  end

  def total_items
    @total_items ||= todo_items.count
  end
end

app/controllers/todo_lists_controller.rb
# frozen_string_literal: true

class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show edit update destroy move]
  before_action :set_project
  before_action :authenticate_user!
  def index
    @todo_lists = @project.todo_lists
  end

  def show
    @todo_item = TodoItem.new
    @project = current_user.projects.friendly.find(params[:project_id])
    @todo_list = @project.todo_lists.find(params[:id])
    @todo_items = @todo_list.todo_items
  end

  def new
    @todo_list = TodoList.new
  end

  def edit; end

  def create
    @todo_list = @project.todo_lists.new(todo_list_params)

    if @todo_list.save
      redirect_to project_todo_lists_path(@project), success: "Todo's group successfully created!"
    else
      render :new
    end
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to project_todo_list_path(@project, @todo_list), notice: "Todo's group successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to [@project, @todo_list], alert: "Todo's group has been deleted!"
  end

  def move
    todo_list = @project.todo_lists.find(params[:id])
    todo_list.update(position: params[:position].to_i)
    todo_list.update(status: params[:status])
    render json: { message: "ok"}
  end

  private

  def set_project
    @project = current_user.projects.friendly.find(params[:project_id])
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:title, :start, :position, :status , todo_items: [:todo_list])
  end

end

app/views/todo_lists/_edit_form.html.erb
<div>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:col-span-3">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Edit Todo List</h3>
      <%= form_with(model:  [@project, todo_list]) do |form| %>
        <% if todo_list.errors.any? %>
          <ul>
            <% todo_list.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="shadow sm:rounded-md sm:overflow-hidden">
          <div class="px-4 py-5 space-y-6 bg-white sm:p-6">
            <div>
              <%= form.label :title, class:"block text-sm font-medium text-gray-700"%>
              <div class="mt-1">
                <%= form.text_field :title, class:"shadow-sm focus:ring-yellow-500 focus:border-yellow-500 mt-1 block w-full h-10 sm:text-sm border border-gray-300 rounded-md pl-2"%>
              </div>
            </div>
          </div>
          <div class="px-4 py-3 text-right bg-gray-50 sm:px-6 ">
            <%= form.submit 'Edit TodoList', class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm rounded-md text-white bg-yellow-600 hover:bg-yellow-400" %>
            <%= link_to 'Back', project_todo_list_path, class:"inline-flex justify-center py-2 px-4 border  rounded-md text-black hover:bg-yellow-400"  %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/todo_lists/_edit_title.html.erb
<%= form_with(model: todo_list ,url:project_todo_list_path(project , todo_list),method: :patch, data:{remote: true}) do |form| %>
  <%= form.text_field :title, class: 'focus:outline-none border border-gray-300 rounded-md p-4 h-8 bg-theme-50' %>
  <%= form.submit 'Update', class: 'theme-fill-btn' %>
<% end %>

app/views/todo_lists/_form.html.erb
<div>
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-3">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Todo List</h3>
      <%= form_with(model:  [@project, todo_list]) do |form| %>
        <% if todo_list.errors.any? %>
          <ul>
            <% todo_list.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="shadow sm:rounded-md sm:overflow-hidden">
          <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
            <div>
              <%= form.label :title, class:"block text-sm font-medium text-gray-700"%>
              <div class="mt-1">
                <%= form.text_field :title, class:"shadow-sm focus:ring-yellow-500 focus:border-yellow-500 mt-1 block w-full h-10 sm:text-sm border border-gray-300 rounded-md", placeholder: "Add New Todo Here"%>
              </div>
            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 ">
            <%= form.submit '新增TodoList', class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-yellow-600 hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-300" %>
            <%= link_to 'Back', project_todo_lists_path, class:"inline-flex justify-center py-2 px-4 border border-transparent border-blue-500 shadow-sm text-sm font-medium rounded-md text-black bg-white-600 hover:bg-white-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"  %>
          </div>
        </div>
    <% end %>
    </div>
  </div>
</div>

app/views/todo_lists/_new_form.html.erb
<div data-controller="modal" data-action="click->modal#close" class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
    <div data-modal-target="container" class="relative bg-theme-5 rounded-lg shadow dark:bg-gray-700">
      <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-medium text-gray-900 dark:text-white">
            New Todos 
        </h3>
        <div>
          <button type="submit" data-action="click->modal#hide">
            <%= icon_tag 'fa-times fa-solid fa-lg pr-3 text-gray-500 hover:text-theme-200' %>
          </button>
        </div>
      </div>
      <div class="m-auto p-8 block w-auto" , data-controller="modal">
          <%= form_with(model:  [@project, todo_list], data:{remote:true}, class:"contents w-full max-w-lg", method: :post) do |form| %>
            <% if todo_list.errors.any? %>
              <ul>
                <% todo_list.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            <% end %>
            <div>
              <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                <div>
                  <%= form.label :title, class:"block text-sm font-medium text-gray-700"%>
                  <div class="mt-1">
                    <%= form.text_field :title, class:"p-4 shadow-sm focus:border-theme-150 focus:outline-none mt-1 block w-full h-10 sm:text-sm border border-gray-300 bg-theme-50 rounded-md", placeholder: "Add New Todo Here"%>
                  </div>
                </div>
              </div>
              <div class="px-4 py-3 bg-gray-50 text-right sm:px-6 ">
                <%= form.submit  class:"theme-fill-btn"  %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todo_lists/_todo_list.html.erb
<div id="<%= dom_id todo_list %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= todo_list.title %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this todo list", todo_list, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this todo list', edit_todo_list_path(todo_list), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/todo_lists/edit.html.erb
<div class="container flex flex-col items-center p-28">
  <div>
      <%= render 'edit_form', todo_list: @todo_list , project:@project %>
  </div>
</div>

app/views/todo_lists/edit.js.erb
var editTodo = "<%= j render "edit_title", todo_list: @todo_list , project:@project %>"
document.querySelector("#dom_id").insertAdjacentHTML('afterend', editTodo ) 

app/views/todo_lists/index.html.erb
<div class="relative h-full max-h-screen min-w-0 py-10 px-4 md:px-28">
  <div class="main-container">
    <div class="w-full m-auto">
      <h1 class="mb-3 text-5xl font-semibold text-gray-700">Todos</h1>
      <div class="py-4 font-medium text-gray-400">
        <p>Make lists of work that needs to get done, assign items, set due dates, and discuss.</p>
      </div>
      <div class="flex justify-end pb-2">
        <%= link_to "NEW", new_project_todo_list_path, class:"theme-fill-btn", data: { remote: true }%>
      </div>
    </div>
    <div class="p-4 m-auto mb-4 border-t border-gray-300">
    </div>
    <div class="container grid grid-cols-1 lg:grid-cols-3 gap-4 max-w-full">
      <ul class="list todos">
        <div class="w-auto px-4 py-4">
            <span class="todo-status-title bg-pink-200 rounded-lg p-2">Todos</span>
            <div class="flex flex-col text-2xl text-center flex-col-3 pt-4 gap-2" data-controller="sortable" data-sortable-status-value="a">
                <% @todo_lists.each do |todo_list| %>
                  <% if todo_list.status === 'todos'  %>
                  <h5 class=" mb-2 text-xl font-medium leading-tight text-yellow-600" status="todos" data-id="<%= todo_list.id %>">
                    <li class="todo-content">
                      <td><%= link_to todo_list.title, project_todo_list_path(@project ,todo_list), class:'text-gray-600 text-xl handle' %></td>
                        <%= link_to project_todo_list_path(@project, todo_list ) , method: "DELETE"  do %>
                        <i class="text-lg far fa-trash-alt"></i>
                        <% end %>
                    </li>
                  </h5>
                <% end %>  
              <% end %>
            </div>
        </div>
      </ul>
      <ul class="list doing">
        <div class="w-auto px-4 py-4" >
          <span class="todo-status-title bg-yellow-200 rounded-lg p-2">Doing</span>
          <div class="flex flex-col text-2xl text-center  flex-col-3 pt-4 gap-2" data-controller="sortable" data-sortable-status-value="b">
          <% @todo_lists.each do |todo_list| %>
                    <% if todo_list.status === 'doing' %>
                      <h5 class="mb-2 text-xl font-medium leading-tight text-yellow-600" data-id="<%= todo_list.id %>">
                        <li class="todo-content">
                          <td><%= link_to todo_list.title, project_todo_list_path(@project ,todo_list),class:'text-gray-600 text-xl handle ' %></td>
                          <%= link_to project_todo_list_path(@project, todo_list ) , method: "DELETE"  do %>
                          <i class="text-lg far fa-trash-alt"></i>
                          <% end %>
                        </li>
                      </h5>
                    <% end %>  
                  <% end %>
            </div>
        </div>
      </ul>
      <ul class="list done">
        <div class="w-auto px-4 py-4">
          <span class="todo-status-title bg-green-200 rounded-lg p-2">Finish</span>
            <div class="flex flex-col text-2xl text-center flex-col-3 pt-4 gap-2" data-controller="sortable" data-sortable-status-value="c">
            <% @todo_lists.each do |todo_list| %>
                    <% if todo_list.status === 'done' %>
                      <h5 class="mb-2 text-xl font-medium leading-tight text-yellow-600" data-id="<%= todo_list.id %>">
                        <li class="todo-content">
                          <td><%= link_to todo_list.title, project_todo_list_path(@project ,todo_list),class:'text-gray-600 text-xl handle' %></td>
                          <%= link_to project_todo_list_path(@project, todo_list ) , method: "DELETE"  do %>
                          <i class="text-lg far fa-trash-alt"></i>
                          <% end %>
                        </li>
                      </h5>
                    <% end %>  
                  <% end %>
            </div>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/todo_lists/new.html.erb
<div class="p-28">
  <h1>New Todo List</h1>
  <%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/new.js.erb
var newTodo = "<%= j render "new_form", todo_list: @todo_list %>"
document.querySelector("#section").innerHTML += newTodo 

app/views/todo_lists/show.html.erb
<div class="relative h-full max-h-screen min-w-0 py-10 overflow-x-hidden px-1 md:px-28" >
  <div class="main-container">
    <div class="w-full m-auto">
      <div data-controller="dropdown">
        <button type="button" data-action="click->dropdown#toggle" class="fixed top-28 right-24 z-10"><%= icon_tag('fa-ellipsis fa-solid fa-xl dropdown-icon')%></button>
        <div data-dropdown-target="toggle"  class="hidden dropdown-content" 
             data-transition-enter-active="transition ease-in-out"
             data-transition-enter-from="transform translate-x-32 opacity-0 scale-x-0"
             data-transition-enter-to="transform translate-x-0 opacity-100 scale-x-100"
             data-transition-leave-active="transition ease-in-out"
             data-transition-leave-from="transform translate-x-0 opacity-100 scale-x-100"
             data-transition-leave-to="transform translate-x-32 opacity-0 scale-x-0">
          <div class="w-full flex justify-end items-center py-2 px-1">
            <button type="submit" data-action="click->dropdown#hide" class="p-3"><%= icon_tag('fa-times fa-solid fa-lg p-2') %></button>
          </div>
          <%=link_to "Edit", edit_project_todo_list_path(@project, @todo_list), class: 'dropdown mt-2', data: { remote: true, action: 'dropdown#hide' } %>
          <%=link_to "Delete", project_todo_list_path, method: "delete", data: { confirm: "Are you sure to delete?", action: 'dropdown#hide'}, class: 'dropdown' %>
          <%=link_to "Return", project_todo_lists_path, class: 'dropdown', data: { action: 'dropdown#hide' }%>
        </div>
      </div>
      <h1 id="dom_id" class="mb-2 text-5xl font-semibold text-gray-700"><%= @todo_list.title %></h1>
      <%= form_for([@project, @todo_list, @todo_item], class: 'w-full') do |form| %>
      <div class="py-1 font-medium text-gray-400">
        <%= @todo_list.percent_complete %>%(<%= @todo_list.completed_items %>/<%= @todo_list.total_items %>)
      </div>
      <div class="flex h-2 my-2 overflow-hidden text-xs rounded bg-amber-200">
        <div style="width: <%= @todo_list.percent_complete %>%" class="flex flex-col justify-center text-center text-white bg-yellow-500 shadow-none whitespace-nowrap"></div>
      </div>
      <div class="py-2">
          <div class="w-full flex justify-start items-center pb-4">
              <div class="w-11/12 ">
                <%= form.text_field :description, 
                                    class:"w-full h-10 p-4 border border-gray-300 bg-theme-50 rounded-md focus:border-theme-150 focus:outline-none",
                                    placeholder:"Add new task",
                                    autocomplete: 'off' %>
              </div>
              <div class="w-1/12 pl-2 pb-0.5">
                <%= form.submit 'NEW', class:'theme-fill-btn' %> 
              </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="max-h-96 pr-1 h-full overflow-x-hidden">
      <div class="flex">
        <ul class="w-full list-group">
          <% @todo_list.todo_items.reverse.each do |todo_item| %>
          <% if todo_item.completed? %>
            <li class="w-full list-group-item ">
              <div class="flex items-center justify-between bg-theme-200 text-theme-5 hover:text-gray-600 rounded-md shadow-md w-full mb-2 border border-gray-300 h-14 hover:bg-theme-180">
                  <span class="ml-4 cursor-default ">
                  <%= todo_item.description %></span>
                  <%= link_to '#', class:' m-auto mr-2 p-2', data: { reflex: 'click->TodoItem#todo_incomplete', id: todo_item.id } do %>
                    <i class="fas fa-undo hover:text-theme-200"></i>
                  <% end %>
                  <%= link_to project_todo_list_todo_item_path(@project, @todo_list, todo_item.id ), method: "delete", class:'mr-2 p-2' do %>
                    <i class="text-lg far fa-trash-alt hover:text-theme-200"></i>
                  <% end %>
              </div>
            </li>
            <% else %>
            <li class="flex w-full list-group-item">
              <div class="flex items-center justify-between rounded-md shadow-md w-full mb-2 border border-gray-300  h-14 hover:bg-theme-180">
                  <span class="ml-4"><%= todo_item.description %></span>
                  <div class="flex justify-start">
                    <%= link_to '#', class: 'm-auto mr-2 p-2', data: { reflex: 'click->TodoItem#todo_complete', id: todo_item.id } do %>
                      <i class="fas fa-check hover:text-theme-200"></i>
                    <% end %>
                    <%= link_to project_todo_list_todo_item_path(@project, @todo_list, todo_item.id ), method: "delete", class:'mr-2 p-2' do %>
                      <i class="text-lg far fa-trash-alt hover:text-theme-200"></i>
                    <% end %>
                  </div>
              </div>
            </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>