config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user  do
    get 'users/info', to: 'users/infos#info'
    post 'users/info', to: 'users/infos#setting'
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        member do
          post :invite_member
        end
      end
    end
  end

  resource :personal, only: [:show]

  resources :projects, except: [:index] do
    resource :bucket, only: [:show] do
      resources :documents, only: %i[create destroy]
    end
    resource :chat_room, only: [:show] do
      resources :contents, only: [:create]
    end
    resources :private_chats, only: [:show] do
      resources :contents, only: [:create]
    end

    resources :schedules
    resources :messages do
      resources :comments, only: %i[create destroy edit]
    end

    resources :todo_lists do
      member do
        patch :move
      end
      resources :todo_items
    end
  end

  mount DocumentUploader.download_endpoint => '/documents', host: 'https://turbocamp.tw'
  mount ImageUploader.download_endpoint => '/images', host: 'https://turbocamp.tw'
end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  # has_many :todo_lists

  validates :title, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :location, presence: true
  belongs_to :project
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[show edit update destroy]
  before_action :set_project
  before_action :authenticate_user!

  def index
    @schedules = @project.schedules
  end

  def show; end

  def new
    @schedule = Schedule.new
  end

  def edit; end

  def create
    @schedule = @project.schedules.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { index }
        format.json { render :show, status: :created, location: [@project, @schedule] }
        format.json { render :show, location: [@project, @schedule] }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: 503 }
      end
    end
  end

  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to project_schedules_path [@project], notice: 'Schedule successfully updated!' }
        format.json { render :show, status: :ok, location: [@project] }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: 503 }
      end
    end
  end

  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html {
        redirect_to [@project, @schedule], alert: 'Schedule has been deleted!'
      }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = current_user.projects.friendly.find(params[:project_id])
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def schedule_params
    params.require(:schedule).permit(:title, :calendar_id, :start, :end, :location)
  end
end

app/views/schedules/_form.html.erb
<%= form_with(model: [@project, schedule] , class: "contents") do |form| %>

  <div class="my-5">
    <%= form.label :title, '事件' %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>



  <div class="my-5">
    <%= form.label :start, '起始時間' %>
    <%= form.text_field :start, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: {controller: "flatpickr"} %>
  </div>

  <div class="my-5">
    <%= form.label :end, '結束時間' %>
    <%= form.text_field :end, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: {controller: "flatpickr"} %>
  </div>

  <div class="my-5">
    <%= form.label :location, '地點' %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :name, '狀態' %>
    <%= form.select :name, ["My Calendar", "Todos", "Finish"], class: "block w-full" %>
  </div>

  <div class="inline">
    <%= form.submit '新增', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div id="<%= schedule %>">
    <p class="my-5">
      <strong class="block mb-1 font-medium">事件:</strong>
      <%= schedule.title %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">起始時間:</strong>
      <%= schedule.start %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">結束時間:</strong>
      <%= schedule.end %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">狀態:</strong>
      <%= schedule.name %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">地點:</strong>
      <%= schedule.location %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this schedule", schedule, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to 'Edit this schedule', edit_schedule_path(schedule), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>

app/views/schedules/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">修改清單</h1>

  <%= render "form", schedule: @schedule, project: @project.slug %>

  <%= link_to "行程", [@project, @schedule], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "回到行事曆", project_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/schedules/index.html.erb
<div class="relative h-full max-h-screen min-w-0 px-4 py-10 md:px-28">
  <div class="main-container">
    <div class="w-full m-auto">
      <h1 class="mb-3 text-5xl font-semibold text-gray-700">Schedule</h1>
      <div class="py-4 font-medium text-gray-400">
        <p>Set important dates on a shared schedule.</p>
      </div>
    </div>
    <div class="p-4 m-auto mb-4 border-t border-gray-300">
    </div>
    <div id="changeStatus">
      <select id="schedule" class="block w-1/5 p-2 mb-2 font-bold border-2 rounded border-theme-200">
        <option selected value="month">Monthly</option>
        <option value="week">Weekly</option>
        <option value="day">Day</option>
      </select>
    </div>
    <div data-controller="calendar" class="border border-gray-500 rounded-lg calendar" data-schedule="<%= @schedules.to_json %>">
      <div id="calendar"></div>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="p-28 w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">新增行程</h1>
  <%= render "form", schedule: @schedule, project: @project.slug %>
  <%= link_to '回到行事曆', project_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-100 inline-block font-medium" %>
</div>

app/views/schedules/show.html.erb
<div class="px-28 py-10 h-full min-w-0 overflow-x-hidden max-h-screen relative">
  <div class="mx-auto">


    <%= render @schedule %>

    <%= link_to '修改行程', edit_project_schedule_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to '刪除行程', project_schedule_path(@project), method: 'delete', class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to '回到行事曆', project_schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>