config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  devise_scope :user  do
    get 'users/info', to: 'users/infos#info'
    post 'users/info', to: 'users/infos#setting'
  end

  root 'home#index'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [] do
        member do
          post :invite_member
        end
      end
    end
  end

  resource :personal, only: [:show]

  resources :projects, except: [:index] do
    resource :bucket, only: [:show] do
      resources :documents, only: %i[create destroy]
    end
    resource :chat_room, only: [:show] do
      resources :contents, only: [:create]
    end
    resources :private_chats, only: [:show] do
      resources :contents, only: [:create]
    end

    resources :schedules
    resources :messages do
      resources :comments, only: %i[create destroy edit]
    end

    resources :todo_lists do
      member do
        patch :move
      end
      resources :todo_items
    end
  end

  mount DocumentUploader.download_endpoint => '/documents', host: 'https://turbocamp.tw'
  mount ImageUploader.download_endpoint => '/images', host: 'https://turbocamp.tw'
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  after_create :create_chat_room
  after_create :create_bucket
  include ImageUploader::Attachment(:image)
  include Slugable

  #  與user多對多關聯
  has_many :personals
  has_many :users, through: :personals, dependent: :destroy

  # 在project內部功能
  has_many :private_chats, dependent: :destroy
  has_one :chat_room, dependent: :destroy
  has_one :bucket, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :schedules,  dependent: :destroy
  has_many :todo_lists, dependent: :destroy
  has_many :todo_lists, -> { order(position: :asc) }

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 50 }

  def normalize_friendly_id(value)
    value.to_s.parameterize(preserve_case: true)
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProjectsController < Api::V1::BaseController
      def invite_member
        user = User.where(email: params[:email]).first
        message = '請重新邀請'
        unless user.nil?
          project = Project.friendly.find(params[:id])
          if project.users.exists?(user.id)
            message = '成員已存在'
          else
            project.users << user
            project.chat_room.users << user 
            message = '成功邀請成員'
          end
        end
        render json: { message: }
      end
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include Pundit::Authorization
  before_action :authenticate_user!
  before_action :find_my_project, only: %i[show edit update destroy]
  
  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_clean)
    current_user.personals.where(project_id: @project.id).update(role: 'owner')
    if @project.save
      @project.chat_room.users << current_user 
      redirect_to project_path(@project), success: 'Project successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    authorize @project, policy_class: ProjectPolicy
    if @project.update(project_clean)
      redirect_back fallback_location: root_path, notice: 'Project successfully updated!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @project, policy_class: ProjectPolicy
    @project.destroy
    redirect_to personal_path, alert: 'Project has been deleted!'
  end

  private

  def project_clean
    params.require(:project).permit(:title, :description, :nickname, :imageurl, :image)
  end

  def find_my_project
    @project = current_user.projects.friendly.find(params[:id])
  end
end

app/views/projects/_edit_form.html.erb
<div data-controller="modal" data-action="click->modal#close" class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-xl h-full md:h-auto">
    <div data-modal-target="container" class="relative bg-theme-5 rounded-lg shadow dark:bg-gray-700">
      <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-medium text-gray-900 dark:text-white">
            Edit Project 
        </h3>
        <div>
          <button type="submit" data-action="click->modal#hide">
            <%= icon_tag('fa-times fa-solid fa-lg pr-3 text-gray-500 hover:text-theme-200') %>
          </button>
        </div>
      </div>
      <%= form_with(model: project , url:project_path(project), class:"w-full px-6 max-w-lg m-auto" , data:{ remote: true }, method: :patch) do |form| %>
        <div class="flex flex-wrap justify-center pt-6 mb-3">
          <div class="rounded-full w-40 h-40 overflow-x-hidden overflow-y-hidden mb-2">
            <%= form.label :image do %>
              <%= image_tag( project.image_url || "logo_a_0" ,data: { modal_target: "output" }, class:" hover:text-black hover:opacity-60 cursor-pointer ") %>
            <% end %>  
            <%= form.file_field :image ,class:'w-full hidden',data: {modal_target: "input", action:"change->modal#readURL" } %>
          </div>
        </div>
        <div class="w-full py-1">
          <%= form.label :title , "Project Name", class:"block normal-case tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
          <%= form.text_field :title , class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"%>
        </div>
        <div class="w-full py-1">
          <%= form.label :description , "Description" , class:"block normal-case tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
          <%= form.text_area :description , class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"%>
        </div>
        <div class="flex justify-end items-center px-5 py-8">
          <%= form.submit "Update" ,class: "theme-fill-btn mr-5 cursor-pointer"%>
          <%= link_to 'Delete Project' , project_path(project) , method: :delete, class: 'theme-fill-btn hover:bg-red-600', data:{ confirm:"Are you sure?" } %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div data-controller="modal" data-action="click->modal#close" class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
    <div data-modal-target="container" class="relative bg-theme-5 rounded-lg shadow dark:bg-gray-700">
      <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-medium text-gray-900 dark:text-white">
            New Project 
        </h3>
        <div>
          <button type="submit" data-action="click->modal#hide">
            <%= icon_tag 'fa-times fa-solid fa-lg pr-3 text-gray-500 hover:text-theme-200' %>
          </button>
        </div>
      </div>
      <div class="border-gray-400 m-auto p-8 block w-auto" , data-controller="modal">
        <%= form_with(model: project ,data:{remote:true},  class:"contents w-full max-w-lg", method: :post) do |form| %>
          <div class="flex flex-wrap justify-center mb-3">
              <div class="rounded-full w-40 h-40 overflow-x-hidden overflow-y-hidden mb-2">
                <%= form.label :image  do%>
                  <%= image_tag( @project.image_url || "logo_a_0" ,data: { modal_target: "output" } , class:"hover:text-black hover:opacity-60 cursor-pointer")%>
                <% end %>
              </div>
              <%= form.file_field :image ,class:'w-full hidden ',data: { modal_target: "input", action:"change->modal#readURL"}%>
          </div>
          <div class="w-full px-3 mb-6 md:mb-0">
            <div>
              <div class="pb-2">
                <%= form.label :title, 'Project Name', class:'tracking-wide text-gray-700 text-xs font-bold mb-4 text-lg normal-case'%>
              </div>
              <%= form.text_field :title , class:'w-full bg-gray-50 text-gray-700 border border-gray-100 rounded py-3 px-4 mb-3 leading-tight'%>
            </div>
          </div>
          <div class="w-full px-3">
            <div>
              <div class="pb-2">
                <%= form.label :description , 'Description' , class:'tracking-wide text-gray-700 text-xs font-bold mb-4 text-lg normal-case'%>
              </div>
              <%= form.text_area :description , class:'p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-100 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white', placeholder: "Your content..." %>
            </div>
          </div>
          <div class="flex justify-end mt-5 pl-1">
            <%= form.submit 'Create Project', class: 'theme-fill-btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_modal.html.erb
<div data-modal-target="container" class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
      <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
          <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
              <h3 class="text-xl font-medium text-gray-900 dark:text-white">
                  New Project 
              </h3>
              <div>
              <%= link_to icons('times', :fas, 'lg', 'pr-3 text-gray-500 hover:text-theme-200'), personal_path %>
              </div>
          </div>
          <div class="border-gray-400 m-auto p-8 flex w-auto">
              <%= form_with(model: @project , class:"w-full max-w-lg ") do |form| %>
                  <div class="w-full px-3 mb-6 md:mb-0">
                      <div>
                          <%= form.label :title , "Title"  , class:"block tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
                          <%= form.text_field :title , class:"block w-full bg-gray-50 text-gray-700 border border-gray-100 rounded py-3 px-4 mb-3 leading-tight"%>
                      </div>
                  </div>
                  <div class="w-full px-3">
                      <div>
                          <%= form.label :description , "Content" , class:"block tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
                          <%= form.text_area :description , class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-100 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white ", placeholder: "Your content..." %>
                      </div>
                  </div>
                  <div class="flex justify-end mt-5 pl-1">
                      <%= form.submit "新增" ,class:"theme-fill-btn"%>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="p-28 h-full min-w-0 overflow-hidden max-h-screen">
  <div class="m-auto w-full flex justify-between">
    <h1 class="text-7xl font-semibold"><%= @project.title %></h1>
    <div class="flex items-center">
    <%= link_to 'Edit Project' , edit_project_path(@project), class: 'theme-fill-btn' %>
    </div>
  </div>
  <div class="p-8 m-auto h-5 border-t border-black"></div>
  <div class="container m-auto p-6 ">
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 grid-flow-row relative ">
      <%= link_to '#', class: 'card' do %>
        <div class="justify-between block p-4 leading-normal">
          <div class="pt-24">
          </div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Todos</h5>
        </div>
      <% end %>
      <%= link_to '#', class: 'card' do %>
        <div class="justify-between block p-4 leading-normal">
          <div class="pt-24"> </div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Schedule</h5>
        </div>
      <% end %>
      <%= link_to project_chat_room_path(@project), class: 'card' do %>
        <div class="justify-between block p-4 leading-normal">
          <div class="pt-24"> </div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Camfire</h5>
        </div>
      <% end %>
      <%= link_to '#', class: 'card' do %>
        <div class="justify-between block p-4 leading-normal">
          <div class="pt-24"> </div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Message Boards</h5>
        </div>
      <% end %>
      <%= link_to '#', class: 'card' do %>
        <div class="justify-between block p-4 leading-normal">
          <div class="pt-24"> </div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Docs & Files</h5>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div data-controller="modal" class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-medium text-gray-900 dark:text-white">
            Edit Project 
        </h3>
        <div>
        <%= link_to icons('times', :fas, 'lg', 'pr-3 text-gray-500 hover:text-theme-200'), project_path(@project) %>
        </div>
      </div>
      <%= form_with(model: @project , class:"w-full max-w-lg") do |form| %>
        <div>
          <div class="flex flex-wrap justify-center mb-3">
              <div class="rounded-full w-40 h-40 overflow-x-hidden overflow-y-hidden mb-2">
                <%= form.label :image do %>
                  <%= image_tag( @project.image_url || "book" ,data: { preview_target: "output" } , class:" hover:text-black hover:opacity-60 cursor-pointer ") %>
                <% end %>  
                <%= form.file_field :image ,class:'w-full hidden',data: {preview_target: "input", action:"change->preview#readURL"}%>
              </div>
        </div>
        <div class="w-full px-6 py-4">
            <div>
                <%= form.label :title , "標題"  , class:"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
                <%= form.text_field :title , class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"%>
            </div>
        </div>
        <div class="w-full px-6 py-4">
            <div>
                <%= form.label :description , "描述" , class:"block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2 text-lg"%>
                <%= form.text_area :description , class:"appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500"%>
            </div>
        </div>
        <div class="flex justify-end items-center px-5 py-4">
          <%= form.submit "更新" ,class: "theme-fill-btn  mr-5"%>
          <%= link_to '刪除專案' , project_path(@project) , method: :delete, class: 'theme-fill-btn' %>
        </div>
      <% end %>
        <div data-controller="member" class="block m-auto" data-id="<%= @project.slug %>">
          <button  data-action="click->member#join" class="px-2 theme-fill-btn">Add Member</button>
          <div id="inputbox" class="hidden px-2 " >
            <input type="text" placeholder="請輸入信箱" class="input">
            <button class="searchbtn theme-fill-btn" data-action="click->member#invite">加入成員</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.js.erb
var editproject = "<%= j render "edit_form" , project:@project %>"
document.querySelector("#section").innerHTML += editproject

app/views/projects/new.html.erb
<section class="p-20 h-full min-w-0 overflow-hidden max-h-screen">
  <div class="m-auto w-11/12">
    <div class="flex justify-end pt-11 pb-3">
      <%= link_to 'NEW', new_project_path, class: 'theme-fill-btn' %>
    </div>
    <div class="p-6 m-auto h-5 border-t border-black"></div>
  </div>
  <div class="container m-auto p-6">
    <div class="grid grid-cols-1 sm:grid-cols-2  
                lg:grid-cols-3 gap-5 grid-flow-row relative ">
    <% current_user.projects.each do |project| %>
      <%= link_to project_path(project), class: 'card' do  %>
        <div class="block justify-between p-4 leading-normal">
          <div class="pt-16"></div>
          <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= project.title%></h5>
          <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= project.description %></p>
          <div class="flex">
          <div class="w-10 h-10 rounded-full overflow-hidden">
          <% project.users.each do |user| %>
            <% if user.avatar %>
              <%= image_tag(user.avatar_url, size:'40x40' , class:'w-full h-full' )%>
            <% else %>
              <% if user.imageurl == nil%>
                <%= image_tag('default_user' , size:'40x40' , class:'w-full h-full')%>
              <% else %>
                <%= image_tag(user.imageurl , size:'40x40' , class:'w-full h-full')%>
              <% end %>
            <% end %>
          <% end %>
          </div>
        </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</section>

<div class="bg-theme-0 bg-opacity-60 overflow-y-auto overflow-x-hidden animated fadeIn fixed inset-0 flex items-center justify-center z-50 w-full md:inset-0 md:h-full">
  <div class="relative p-4 max-h-screen w-full max-w-lg h-full md:h-auto">
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <div class="flex justify-between items-center p-5 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-medium text-gray-900 dark:text-white">
            New Project 
        </h3>
        <div>
        <%= link_to icons('times', :fas, 'lg', 'pr-3 text-gray-500 hover:text-theme-200'), personal_path %>
        </div>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/projects/new.js.erb
var newproject = "<%= j render "form" , project:@project %>"
document.querySelector("#personal").innerHTML += newproject

app/views/projects/show.html.erb
<div class="px-4 md:px-28 py-10 min-w-0 max-h-max bg-theme-5 h-screen">
  <div class="main-container">
    <div class="m-auto w-full flex justify-between">
      <h1 class="text-5xl mb-3 font-semibold text-gray-700"><%= @project.title %></h1>
    </div>
    <div class="font-medium text-gray-400 py-4">
      <p><%= @project.description %></p>
    </div>
    <div class="p-4 m-auto mb-4 border-b border-gray-300">
    </div>
  </div>
  <div class="main-container">
    <div class="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 3xl:grid-cols-5 gap-7">
      <%= link_to project_todo_lists_path(@project), class: 'project-card' do %>
        <div class="flex flex-col items-center align-middle w-full p-4 h-full  ">
          <div class="feat-icon">
            <%= image_tag('icon02', size: '80x80', class: 'm-4') %>
          </div>
          <div>
            <h5 class="feat-title">Todos</h5>
          </div>
          <div>
            <p class="feat-info">Make lists of work that needs to get done, assign items, set due dates, and discuss.</p> 
          </div>
        </div>
      <% end %>
      <%= link_to project_schedules_path(@project), class: 'project-card' do %>
        <div class="flex flex-col items-center align-middle w-full p-4">
          <div class="feat-icon">
            <%= image_tag('icon04', size: '80x80', class: 'm-4') %>
          </div>
          <div>
            <h5 class="feat-title">Schedule</h5>
          </div>
          <div>
            <p class="feat-info">Set important dates on a shared schedule. And connect with todos to set the schedule.</p> 
          </div>
        </div>
      <% end %>
      <%= link_to project_chat_room_path(@project), class: 'project-card' do %>
        <div class="flex flex-col items-center align-middle w-full p-4">
          <div class="feat-icon">
            <%= image_tag('icon03', size: '80x80', class: 'm-4') %>
          </div>
          <div>
            <h5 class="feat-title">Chatroom</h5>
          </div>
          <div>
            <p class="feat-info">Chat casually with the group, ask random questions, and share stuff without ceremony.</p> 
          </div>
        </div>
      <% end %>
      <%= link_to project_messages_path(@project) , class: 'project-card' do %>
        <div class="flex flex-col items-center align-middle w-full p-4">
          <div class="feat-icon">
            <%= image_tag('icon01', size: '80x80', class: 'm-4') %>
          </div>
          <div>
            <h5 class="feat-title">Message Boards</h5>
          </div>
          <div>
            <p class="feat-info">Post announcements, pitch ideas, progress updates, etc. and keep feedback on-topic.</p> 
          </div>
        </div>
      <% end %>
      <%= link_to project_bucket_path(@project) , class: 'project-card' do %>
        <div class="flex flex-col items-center align-middle w-full p-4">
          <div class="feat-icon">
            <%= image_tag("icon05", size: '80x80', class: 'm-4') %>
          </div>
          <div>
            <h5 class="feat-title">Upload</h5>
          </div>
          <div>
            <p class="feat-info">Share docs, files, images, and spreadsheets. Organize in folders so they’re easy to find.</p> 
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>